sudo: false
dist: trusty

addons:
  apt:
    packages:
      - libgd2-noxpm-dev # Required for gnuplot png terminal
      
language: perl

env:
  gp_version=5.2.4 with_pdl_graphics_gnuplot=1
  
perl:
    - 5.30
    - 5.28
    - 5.26
    - 5.24
    - 5.22
    - 5.20

matrix:
  include:
    - perl: 5.24
      env: gp_version=5.2.4 with_pdl_graphics_gnuplot=0

before_install:
  # Prevent "Please tell me who you are" errors for certain DZIL configs
  - git config --global user.name "TravisCI"

install:
  # Install gnuplot 5 for plot tests. (Not available on Ubuntu 12.04 / 14.04)
  - cd /tmp
  - wget https://github.com/lab-measurement/Lab-Measurement-Homepage/raw/master/gnuplot-5.2.4.tar.gz
  - tar -xf gnuplot-$gp_version.tar.gz
  - cd gnuplot-$gp_version
  - ./configure --prefix=$HOME/local
  - make -j2
  - make install
  - export PATH="$HOME/local/bin:$PATH"
  - gnuplot --version
  # Sometimes Alien::Gnuplot does not find the installed gnuplot
  # (but problem not reproducible, see
  # https://travis-ci.org/lab-measurement/Lab-Measurement/jobs/378743671
  - export GNUPLOT_BINARY=/home/travis/local/bin/gnuplot

  # Install the DZIL dependencies
  # - cpanm  --notest --skip-satisfied Dist::Zilla
  - cpanm -v Dist::Zilla

  # Install DZIL plugins etc if needed
  - cd $TRAVIS_BUILD_DIR
  - dzil authordeps --missing | grep -vP '[^\w:]' | xargs cpanm  --notest

  # install dependencies
  - travis_wait dzil listdeps --missing --cpanm | grep -vP '[^\w:~"\.]' | xargs cpanm  --notest
  - if [ $with_pdl_graphics_gnuplot -eq "1" ]; then cpanm --verbose -f PDL::Graphics::Gnuplot; fi
  - cpanm -n Test::Perl::Critic

script:
  # "normal" tests
  - prove --verbose -l -s -r t
  
  # Perl::Critic tests
  - prove --verbose -l -r xt/critic/

  # Pod manual test
  - prove --verbose xt/pod-manual-coverage.t
  
notifications:
  email: false
  irc: 
    channels: "chat.freenode.net#labmeasurement"
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: true
