name: "IRC Notification"
on: [push, pull_request, create, issues]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: irc push
        uses: rectalogic/notify-irc@v1
        if: github.event_name == 'push'
        with:
          channel: "#labmeasurement"
          server: "irc.libera.chat"
          nickname: lm-notify
          message: |
            ${{ github.actor }} pushed ${{ github.event.ref }} ${{ github.event.compare }}
            ${{ join(github.event.commits.*.message) }}
      - name: irc pull request
        uses: rectalogic/notify-irc@v1
        if: github.event_name == 'pull_request'
        with:
          channel: "#labmeasurement"
          server: "irc.libera.chat"
          nickname: lm-notify
          message: |
            ${{ github.actor }} opened PR ${{ github.event.pull_request.html_url }}
      - name: irc tag created
        uses: rectalogic/notify-irc@v1
        if: github.event_name == 'create' && github.event.ref_type == 'tag'
        with:
          channel: "#labmeasurement"
          server: "irc.libera.chat"          
          nickname: lm-notify
          message: |
            ${{ github.actor }} tagged ${{ github.repository }} ${{ github.event.ref }}
      - name: issue created
        uses: rectalogic/notify-irc@v1
        if: github.event_name == 'issues' && github.event.ref_type == 'opened'
        with:
          channel: "#labmeasurement"
          server: "irc.libera.chat"
          nickname: lm-notify
          message: |
            ${{ github.actor }} opened issue ${{ github.event.issue.html_url }}
            ${{ github.event.issue.title }}
