name: learn-github-actions
on: [push]
jobs:
  'prove-lrt':
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.34'
      - run: pwd
      - run: ls -a
      - run: whoami
      - run: ls -la .github/scripts/
      - name: prove-test
        run: ./.github/scripts/prove-test.bash
        shell: bash
        env:
          gp_version: 5.2.4
          with_pdl_graphics_gnuplot: 1
      
      
